# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/trove-newspaper-harvester',
                'doc_host': 'https://wragge.github.io',
                'git_url': 'https://github.com/wragge/trove-newspaper-harvester',
                'lib_path': 'trove_newspaper_harvester'},
  'syms': { 'trove_newspaper_harvester.core': { 'trove_newspaper_harvester.core.foo': ( 'core.html#foo',
                                                                                        'trove_newspaper_harvester/core.py')}}}